---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  6379: "default/redis-server:6379"
  8086: "default/ui-service:8086"
  8085: "default/serverstatus-service:8085"
