---
- hosts: ansiblehost

  tasks:
  - name: copy dist to docker
    command: cp -pr /local/serveruistatus/dist /local/serveruistatus/docker/.

  - name: create node image
    command: docker build -t serveruistatus:latest .
    args:
     chdir: /local/serveruistatus/docker

  - name: create tag to push image onto docker hub
    command: docker tag serveruistatus:latest birdseyrk/serveruistatus:latest

  - name: push docker image
    command: docker push birdseyrk/serveruistatus:latest
